# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  omdb_api_key: 5ac6c144

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e88d2d80fbe213764780d1feee08efb92ed5359873c9996a6e9ba712d359cdeade60c4ab03f00ffc2e3b6dfc7203827f19020caee27c1b790d3631f45a7f80b9

test:
  secret_key_base: 02c12071f7e759d75115e2b7deee693da0eb9560e0f15c39560a16b5d7b5709bcb91df613477bff389377002dddf240f237d8aab1c430feca31752adcf1ba2c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
